# Generated by Django 3.2.7 on 2021-11-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Agriculture, Food & Natural Resources', 'Agriculture, Food & Natural Resources'), ('Architecture & Construction', 'Architecture & Construction'), ('Arts, A/V Technology & Communications', 'Arts, A/V Technology & Communications'), ('Business Management & Administration', 'Business Management & Administration'), ('Education & Training', 'Education & Training'), ('Finance', 'Finance'), ('Government & Public Administration', 'Government & Public Administration'), ('Health Science', 'Health Science'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Human Services', 'Human Services'), ('Information Technology', 'Information Technology'), ('Law, Public Safety, Corrections & Securit', 'Law, Public Safety, Corrections & Securit'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Science, Technology, Engineering & Mathematics', 'Science, Technology, Engineering & Mathematics'), ('Transportation, Distribution & Logistics', 'Transportation, Distribution & Logistics')], max_length=100, null=True)),
                ('qution', models.CharField(blank=True, max_length=200, null=True)),
                ('ans1', models.CharField(blank=True, max_length=200, null=True)),
                ('ans2', models.CharField(blank=True, max_length=200, null=True)),
                ('ans3', models.CharField(blank=True, max_length=200, null=True)),
                ('ans4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans5', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
