# Generated by Django 3.2.7 on 2022-02-01 13:44

import CareerManagementSystem.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfCarrer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('college', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('aboutUs', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('carrer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeaturedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.student_featured_article)),
                ('articleApprove', models.CharField(blank=True, max_length=400, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorApproveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentChoices', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=400, null=True)),
                ('articleApprove', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined')], max_length=400, null=True)),
                ('ammount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrer')),
                ('studentArticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.studentfeaturedarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timeFrom', models.TimeField(blank=True, null=True)),
                ('timeTo', models.TimeField(blank=True, null=True)),
                ('isBook', models.BooleanField(default=False)),
                ('bookedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='CarrerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=400, null=True)),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.Banner_directory_path_main)),
                ('description', models.TextField(blank=True, null=True)),
                ('carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrer')),
            ],
        ),
        migrations.AddField(
            model_name='carrer',
            name='carrerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrertype'),
        ),
        migrations.CreateModel(
            name='BookUserSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellorSlot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.counsellorslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
