# Generated by Django 3.2.7 on 2021-11-13 04:43

import CareerManagementSystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(blank=True, max_length=500, null=True)),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.Banner_directory_path_main)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industryData', to='CareerManagementSystem.careercategory')),
            ],
        ),
    ]
