# Generated by Django 3.2.7 on 2022-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0002_alter_counsellor_carrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeaturedarticle',
            name='articleApprove',
            field=models.CharField(blank=True, default='Panding', max_length=400, null=True),
        ),
    ]
