# Generated by Django 3.2.7 on 2022-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0002_course_bannerimage2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercategory',
            name='industry',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
