# Generated by Django 3.2.7 on 2022-02-03 15:49

import CareerManagementSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0003_alter_studentfeaturedarticle_articleapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrerpage',
            name='thumbnailImage',
            field=models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.Banner_directory_path_main),
        ),
    ]
