# Generated by Django 3.2.7 on 2022-02-03 15:58

import CareerManagementSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0004_carrerpage_thumbnailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeaturedarticle',
            name='thumbnailImage',
            field=models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.student_featured_article),
        ),
        migrations.AddField(
            model_name='studentfeaturedarticle',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeaturedarticle',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
