# Generated by Django 3.2.7 on 2022-02-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0006_articlenoview_articlerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenoview',
            name='ipAddress',
        ),
        migrations.AlterField(
            model_name='articlenoview',
            name='editorApproveArticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noViewArticle', to='CareerManagementSystem.editorapprovearticle'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='editorApproveArticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleByRating', to='CareerManagementSystem.editorapprovearticle'),
        ),
    ]
