# Generated by Django 3.2.7 on 2022-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0007_auto_20220204_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorapprovearticle',
            name='noView',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='editorapprovearticle',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
