# Generated by Django 3.2.7 on 2022-02-04 11:26

import CareerManagementSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0008_auto_20220204_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=CareerManagementSystem.models.counsellor_carrer),
        ),
    ]
