# Generated by Django 3.2.7 on 2022-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerManagementSystem', '0010_counsellornoview_counsellorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='noView',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
