# Generated by Django 3.2.7 on 2022-02-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CareerManagementSystem', '0011_auto_20220205_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSlotPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_ID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXN_AMOUNT', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, max_length=400, null=True)),
                ('gateway', models.CharField(blank=True, max_length=400, null=True)),
                ('bankname', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNDATE', models.CharField(blank=True, max_length=400, null=True)),
                ('RESPCODE', models.CharField(blank=True, max_length=400, null=True)),
                ('CURRENCY', models.CharField(blank=True, max_length=400, null=True)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=400, null=True)),
                ('MID', models.CharField(blank=True, max_length=400, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('slotBook', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.bookuserslot')),
                ('user', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_ID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXN_AMOUNT', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, max_length=400, null=True)),
                ('gateway', models.CharField(blank=True, max_length=400, null=True)),
                ('bankname', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNDATE', models.CharField(blank=True, max_length=400, null=True)),
                ('RESPCODE', models.CharField(blank=True, max_length=400, null=True)),
                ('CURRENCY', models.CharField(blank=True, max_length=400, null=True)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=400, null=True)),
                ('MID', models.CharField(blank=True, max_length=400, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.editorapprovearticle')),
                ('user', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
