# Generated by Django 3.2.7 on 2021-11-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0002_questionmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('testInstruction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testschedulemanagement',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AptitueTestManagement.grade'),
        ),
        migrations.AlterField(
            model_name='questionmanagement',
            name='industry',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='AptitueTestManagement.carrercategory'),
        ),
    ]
