# Generated by Django 3.2.7 on 2021-11-16 07:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0008_alter_questionmanagement_ans5'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('ans1', models.CharField(blank=True, max_length=200, null=True)),
                ('ans2', models.CharField(blank=True, max_length=200, null=True)),
                ('ans3', models.CharField(blank=True, max_length=200, null=True)),
                ('ans4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans5', models.CharField(blank=True, max_length=200, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
