# Generated by Django 3.2.7 on 2021-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0011_auto_20211117_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
