# Generated by Django 3.2.7 on 2021-11-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0012_testresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmanagement',
            name='grade',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='AptitueTestManagement.grade'),
        ),
    ]
