# Generated by Django 3.2.7 on 2021-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0013_questionmanagement_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedTestGrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definedValue', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
