# Generated by Django 3.2.7 on 2021-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0014_definedtestgrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='industry_Grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
