# Generated by Django 3.2.7 on 2021-11-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0017_auto_20211127_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definedtestgrate',
            old_name='fhour',
            new_name='four',
        ),
    ]
