# Generated by Django 3.2.7 on 2021-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0018_rename_fhour_definedtestgrate_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='definedtestgrate',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
