# Generated by Django 3.2.7 on 2021-11-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0019_definedtestgrate_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definedtestgrate',
            name='definedValueFrom',
        ),
        migrations.RemoveField(
            model_name='definedtestgrate',
            name='definedValueTo',
        ),
    ]
