# Generated by Django 3.2.7 on 2021-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0023_auto_20211204_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrycategory',
            name='industry_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
