# Generated by Django 3.2.7 on 2021-12-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0024_industrycategory_industry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmanagement',
            old_name='ans1',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='questionmanagement',
            old_name='ans2',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='questionmanagement',
            old_name='ans3',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='questionmanagement',
            old_name='ans4',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='questionmanagement',
            old_name='ans5',
            new_name='e',
        ),
    ]
