# Generated by Django 3.2.7 on 2021-12-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptitueTestManagement', '0025_auto_20211208_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmanagement',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
