# Generated by Django 3.2.7 on 2021-12-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('point', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
        ),
        migrations.CreateModel(
            name='InterpretationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newClass', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectTest', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeOptionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('a', models.CharField(blank=True, max_length=400, null=True)),
                ('b', models.CharField(blank=True, max_length=400, null=True)),
                ('c', models.CharField(blank=True, max_length=400, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
        migrations.CreateModel(
            name='ShowGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=400, null=True)),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
                ('selectGrade', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.interpretationgrade')),
            ],
        ),
        migrations.CreateModel(
            name='SelectNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('c', models.FloatField(blank=True, null=True)),
                ('d', models.FloatField(blank=True, null=True)),
                ('e', models.FloatField(blank=True, null=True)),
                ('rightAns', models.FloatField(blank=True, null=True)),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('totalCount', models.IntegerField(blank=True, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('industry_Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('typeOftest', models.CharField(blank=True, max_length=200, null=True)),
                ('totalNo', models.CharField(blank=True, max_length=200, null=True)),
                ('interpretatio', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.interpretation')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('a', models.CharField(blank=True, max_length=400, null=True)),
                ('b', models.CharField(blank=True, max_length=400, null=True)),
                ('c', models.CharField(blank=True, max_length=400, null=True)),
                ('d', models.CharField(blank=True, max_length=400, null=True)),
                ('e', models.CharField(blank=True, max_length=400, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
        migrations.CreateModel(
            name='OneOptionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('a', models.CharField(blank=True, max_length=400, null=True)),
                ('b', models.CharField(blank=True, max_length=400, null=True)),
                ('c', models.CharField(blank=True, max_length=400, null=True)),
                ('d', models.CharField(blank=True, max_length=400, null=True)),
                ('rightAns', models.CharField(blank=True, max_length=300, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
        migrations.AddField(
            model_name='interpretation',
            name='className',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass'),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='grade',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.showgrade'),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='section',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section'),
        ),
        migrations.CreateModel(
            name='ImageOptionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(blank=True, max_length=200, null=True, upload_to='8th')),
                ('a', models.ImageField(blank=True, max_length=200, null=True, upload_to='8th')),
                ('b', models.ImageField(blank=True, max_length=200, null=True, upload_to='8th')),
                ('c', models.ImageField(blank=True, max_length=200, null=True, upload_to='8th')),
                ('d', models.ImageField(blank=True, max_length=200, null=True, upload_to='8th')),
                ('rightAns', models.CharField(blank=True, max_length=300, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
        migrations.CreateModel(
            name='FiveOptionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('a', models.CharField(blank=True, max_length=400, null=True)),
                ('b', models.CharField(blank=True, max_length=400, null=True)),
                ('c', models.CharField(blank=True, max_length=400, null=True)),
                ('d', models.CharField(blank=True, max_length=400, null=True)),
                ('e', models.CharField(blank=True, max_length=400, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
        migrations.CreateModel(
            name='AddTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
                ('selectNumber', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.selectnumber')),
                ('title', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.title')),
                ('typeOfTest', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.testcategory')),
            ],
        ),
    ]
