# Generated by Django 3.2.7 on 2021-12-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='totalNo',
            new_name='totalNoQu',
        ),
    ]
