# Generated by Django 3.2.7 on 2021-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0007_reports_carrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoptionstest',
            name='aText',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='bText',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='cText',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='dText',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='questionText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
