# Generated by Django 3.2.7 on 2021-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0008_auto_20211228_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneoptionstest',
            name='questionImage',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='MultiImage'),
        ),
    ]
