# Generated by Django 3.2.7 on 2021-12-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0009_oneoptionstest_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoptionstest',
            name='e',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='eText',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='a',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='b',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='c',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='d',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='question',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Test'),
        ),
    ]
