# Generated by Django 3.2.7 on 2021-12-28 16:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0010_auto_20211228_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainHeading', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('point', models.TextField(blank=True, null=True)),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
            ],
        ),
    ]
