# Generated by Django 3.2.7 on 2021-12-29 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MultipalTestAdd', '0011_resulttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(blank=True, max_length=400, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('carrer', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.career')),
                ('className', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.newclass')),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
                ('typeOfTest', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.testcategory')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
