# Generated by Django 3.2.7 on 2021-12-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0013_auto_20211229_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbackuponequizecorrect',
            name='testDiscription',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addtest'),
        ),
        migrations.AddField(
            model_name='testbackuponequizecorrect',
            name='userClickObj',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
