# Generated by Django 3.2.7 on 2021-12-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0015_testbackupfivequize_testbackupmultipalquize_testbackuponeimagequizecorrect_testbackupthreequize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbackupfivequize',
            name='oneQuizeCorrect',
        ),
        migrations.RemoveField(
            model_name='testbackupmultipalquize',
            name='oneQuizeCorrect',
        ),
        migrations.RemoveField(
            model_name='testbackuponeimagequizecorrect',
            name='oneQuizeCorrect',
        ),
        migrations.RemoveField(
            model_name='testbackupthreequize',
            name='oneQuizeCorrect',
        ),
        migrations.AddField(
            model_name='testbackupfivequize',
            name='fiveQuize',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.fiveoptionstest'),
        ),
        migrations.AddField(
            model_name='testbackupmultipalquize',
            name='multipalQuize',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.optionstest'),
        ),
        migrations.AddField(
            model_name='testbackuponeimagequizecorrect',
            name='imageOneQuizeCorrect',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.imageoptionstest'),
        ),
        migrations.AddField(
            model_name='testbackupthreequize',
            name='threeQuize',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.threeoptionstest'),
        ),
    ]
