# Generated by Django 3.2.7 on 2021-12-31 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0016_auto_20211229_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtest',
            name='resultTitle',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.resulttitle'),
        ),
        migrations.AddField(
            model_name='resulttitle',
            name='typeOfTest',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.testcategory'),
        ),
    ]
