# Generated by Django 3.2.7 on 2021-12-31 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MultipalTestAdd', '0018_addtest_createat'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbackupfivequize',
            name='lastTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testbackupmultipalquize',
            name='lastTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testbackuponeimagequizecorrect',
            name='lastTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testbackuponequizecorrect',
            name='lastTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testbackupthreequize',
            name='lastTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfTest', models.CharField(blank=True, max_length=400, null=True)),
                ('Class', models.CharField(blank=True, max_length=400, null=True)),
                ('ORDER_ID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXN_AMOUNT', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, max_length=400, null=True)),
                ('gateway', models.CharField(blank=True, max_length=400, null=True)),
                ('bankname', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNID', models.CharField(blank=True, max_length=400, null=True)),
                ('TXNDATE', models.CharField(blank=True, max_length=400, null=True)),
                ('paymentCount', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
