# Generated by Django 3.2.7 on 2021-12-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0019_auto_20211231_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='CURRENCY',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='MID',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='PAYMENTMODE',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='RESPCODE',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
