# Generated by Django 3.2.7 on 2022-01-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0022_auto_20220103_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSection', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='addtest',
            options={'verbose_name_plural': 'Add Test'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name_plural': 'Add Career'},
        ),
        migrations.AlterModelOptions(
            name='fiveoptionstest',
            options={'verbose_name_plural': 'Add Five Options Type Test'},
        ),
        migrations.AlterModelOptions(
            name='imageoptionstest',
            options={'verbose_name_plural': 'Add Image Type Test'},
        ),
        migrations.AlterModelOptions(
            name='interpretation',
            options={'verbose_name_plural': 'Add Grades Wise Interpretation'},
        ),
        migrations.AlterModelOptions(
            name='interpretationgrade',
            options={'verbose_name_plural': 'Add Grades Name'},
        ),
        migrations.AlterModelOptions(
            name='newclass',
            options={'verbose_name_plural': 'Add Classes'},
        ),
        migrations.AlterModelOptions(
            name='oneoptionstest',
            options={'verbose_name_plural': 'Add Single Marking Type Test'},
        ),
        migrations.AlterModelOptions(
            name='optionstest',
            options={'verbose_name_plural': 'Add Multiple Marking Type Test'},
        ),
        migrations.AlterModelOptions(
            name='resulttitle',
            options={'verbose_name_plural': 'Add Report Title'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Add Section'},
        ),
        migrations.AlterModelOptions(
            name='selectacademic',
            options={'verbose_name_plural': 'Add Working Professional & College'},
        ),
        migrations.AlterModelOptions(
            name='selectnumber',
            options={'verbose_name_plural': 'Add Options Marking in each Questions'},
        ),
        migrations.AlterModelOptions(
            name='showgrade',
            options={'verbose_name_plural': 'Add Grades Marking'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name_plural': 'Define Type Of Test'},
        ),
        migrations.AlterModelOptions(
            name='threeoptionstest',
            options={'verbose_name_plural': 'Add Three Options Type Test'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'Test Title of Classes'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='classSection',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='classSection',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='addtest',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='resulttitle',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='selectnumber',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='showgrade',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='testbackupfivequize',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='testbackupmultipalquize',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='testbackuponeimagequizecorrect',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='testbackuponequizecorrect',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='testbackupthreequize',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
        migrations.AddField(
            model_name='title',
            name='classSection',
            field=models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.addclasssection'),
        ),
    ]
