# Generated by Django 3.2.7 on 2022-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0023_auto_20220111_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbackupthreequize',
            name='number',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
