# Generated by Django 3.2.7 on 2022-01-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0024_testbackupthreequize_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbackupthreequize',
            name='createAt',
        ),
    ]
