# Generated by Django 3.2.7 on 2022-01-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0026_auto_20220127_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='CreateAt',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='industry_Grade',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='question',
        ),
    ]
