# Generated by Django 3.2.7 on 2022-02-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0028_auto_20220208_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneoptionstest',
            name='rightAns',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=300, null=True),
        ),
    ]
