# Generated by Django 3.2.7 on 2022-02-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0029_alter_oneoptionstest_rightans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageoptionstest',
            options={},
        ),
        migrations.AddField(
            model_name='reports',
            name='sectionObj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='sectionInterest',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
