# Generated by Django 3.2.7 on 2022-02-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0030_auto_20220208_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='sectionObj',
        ),
        migrations.AddField(
            model_name='reports',
            name='sectionInterest',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
