# Generated by Django 3.2.7 on 2022-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0031_auto_20220208_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
