# Generated by Django 3.2.7 on 2022-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0032_auto_20220208_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageoptionstest',
            options={'verbose_name_plural': 'Image Test'},
        ),
        migrations.AddField(
            model_name='imageoptionstest',
            name='choiceRightAns',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='oneoptionstest',
            name='choiceRightAns',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='rightAns',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='oneoptionstest',
            name='rightAns',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
