# Generated by Django 3.2.7 on 2022-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0033_auto_20220209_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoptionstest',
            name='choiceRightAns',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AText', 'AText'), ('B', 'B'), ('BText', 'BText'), ('C', 'C'), ('CText', 'CText'), ('D', 'D'), ('DText', 'DText'), ('E', 'E'), ('EText', 'EText')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='oneoptionstest',
            name='choiceRightAns',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AText', 'AText'), ('B', 'B'), ('BText', 'BText'), ('C', 'C'), ('CText', 'CText'), ('D', 'D'), ('DText', 'DText'), ('E', 'E'), ('EText', 'EText')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='totalCount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='totalNoQu',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
