# Generated by Django 3.2.7 on 2022-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0034_auto_20220210_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionInterest', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionInterest',
            field=models.BooleanField(default=False),
        ),
    ]
