# Generated by Django 3.2.7 on 2022-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0036_auto_20220211_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiveoptionstest',
            name='question',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='aText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='bText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='cText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='dText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='eText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoptionstest',
            name='question',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='optionstest',
            name='question',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='resulttitle',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttitle',
            name='point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threeoptionstest',
            name='question',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
