# Generated by Django 3.2.7 on 2022-02-11 10:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0037_auto_20220211_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
