# Generated by Django 3.2.7 on 2022-02-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0038_alter_imageoptionstest_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarrerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('carrer', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.career')),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='MultipalTestAdd.section')),
            ],
        ),
    ]
