# Generated by Django 3.2.7 on 2022-02-13 05:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0039_auto_20220212_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
