# Generated by Django 3.2.7 on 2022-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0040_alter_imageoptionstest_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
