# Generated by Django 3.2.7 on 2022-03-18 01:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0042_auto_20220305_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttitle',
            name='pointDiscription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
