# Generated by Django 3.2.7 on 2022-03-18 01:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0043_alter_resulttitle_pointdiscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttitle',
            name='discription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
