# Generated by Django 3.2.7 on 2022-03-18 01:52

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0044_alter_resulttitle_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttitle',
            name='discription',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttitle',
            name='pointDiscription',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
