# Generated by Django 3.2.7 on 2022-03-18 01:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0045_auto_20220318_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttitle',
            name='discription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttitle',
            name='pointDiscription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
