# Generated by Django 3.2.7 on 2022-03-18 03:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0046_auto_20220318_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='generalInstructions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiveoptionstest',
            name='question',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='imageoptionstest',
            name='questionText',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoptionstest',
            name='question',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionstest',
            name='question',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='threeoptionstest',
            name='question',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
