# Generated by Django 3.2.7 on 2022-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipalTestAdd', '0048_alter_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
