# Generated by Django 3.2.7 on 2021-12-10 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefineClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=200, null=True)),
                ('testInstruction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefinedGrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(blank=True, default=0, null=True)),
                ('two', models.IntegerField(blank=True, default=0, null=True)),
                ('three', models.IntegerField(blank=True, default=0, null=True)),
                ('four', models.IntegerField(blank=True, default=0, null=True)),
                ('five', models.IntegerField(blank=True, default=0, null=True)),
                ('six', models.IntegerField(blank=True, default=0, null=True)),
                ('seven', models.IntegerField(blank=True, default=0, null=True)),
                ('eight', models.IntegerField(blank=True, default=0, null=True)),
                ('nine', models.IntegerField(blank=True, default=0, null=True)),
                ('ten', models.IntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('toFromPair', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_Id', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_9th.defineclasses')),
            ],
        ),
        migrations.CreateModel(
            name='Reports_9th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('totalCount', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('industry_Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=200, null=True)),
                ('a', models.CharField(blank=True, max_length=200, null=True)),
                ('b', models.CharField(blank=True, max_length=200, null=True)),
                ('c', models.CharField(blank=True, max_length=200, null=True)),
                ('d', models.CharField(blank=True, max_length=200, null=True)),
                ('e', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_9th.defineclasses')),
                ('industry', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_9th.industrycategory')),
            ],
        ),
    ]
