# Generated by Django 3.2.7 on 2021-12-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10th_interest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showgrade',
            name='area',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
