# Generated by Django 3.2.7 on 2021-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10th_interest', '0002_showgrade_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='f',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='g',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='h',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='i',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='j',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='k',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='l',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='m',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='n',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='o',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='p',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='q',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='r',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='s',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='t',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports_10th_int',
            name='ans9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
