# Generated by Django 3.2.7 on 2021-12-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10th_interest', '0003_auto_20211214_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation_10th_Int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleImportance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
