# Generated by Django 3.2.7 on 2021-12-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10th_interest', '0004_generalinformation_10th_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='showgrade',
            name='HigeScore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
