# Generated by Django 3.2.7 on 2021-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10th_interest', '0005_showgrade_higescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_10th_int',
            name='totalCount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
