# Generated by Django 3.2.7 on 2022-02-08 03:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add Grades Name',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfSection', models.CharField(blank=True, choices=[('Interest', 'Interest')], max_length=300, null=True)),
                ('section', models.CharField(blank=True, max_length=400, null=True)),
                ('timeDuration', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=400, null=True)),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.section')),
                ('selectGrade', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.interpretationgrade')),
            ],
            options={
                'verbose_name_plural': 'Add Grades Marking',
            },
        ),
        migrations.CreateModel(
            name='SelectNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberEachQuestion', models.FloatField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.section')),
            ],
            options={
                'verbose_name_plural': 'Add Options Marking in each Questions',
            },
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('point', models.CharField(blank=True, max_length=400, null=True)),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
                ('the_title', jsonfield.fields.JSONField(default=dict)),
                ('grade', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.showgrade')),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.section')),
                ('selectGrade', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.interpretationgrade')),
            ],
            options={
                'verbose_name_plural': 'Add Grades Wise Interpretation',
            },
        ),
        migrations.CreateModel(
            name='AddQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField(blank=True, null=True)),
                ('question', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('a', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('aText', models.TextField(blank=True, null=True)),
                ('b', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('bText', models.TextField(blank=True, null=True)),
                ('c', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('cText', models.TextField(blank=True, null=True)),
                ('d', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('dText', models.TextField(blank=True, null=True)),
                ('e', models.ImageField(blank=True, max_length=200, null=True, upload_to='Image-Interest')),
                ('eText', models.TextField(blank=True, null=True)),
                ('rightAns', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=300, null=True)),
                ('section', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterestTest.section')),
            ],
        ),
    ]
