# Generated by Django 3.2.7 on 2022-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCarrer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='videoLink',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
