# Generated by Django 3.2.7 on 2022-02-03 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CareerManagementSystem', '0003_alter_studentfeaturedarticle_articleapprove'),
        ('videoCarrer', '0002_alter_youtubevideo_videolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCarrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('sortDescription', models.TextField(blank=True, null=True)),
                ('embedUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('earnings', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=400, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('noView', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerManagementSystem.carrer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
