# Generated by Django 3.2.7 on 2022-02-04 11:26

from django.db import migrations, models
import videoCarrer.models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCarrer', '0004_videonoview_videorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocarrer',
            name='thumbnailImage',
            field=models.ImageField(blank=True, null=True, upload_to=videoCarrer.models.video_carrer),
        ),
    ]
