# Generated by Django 3.2.7 on 2021-12-01 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Define_Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=200, null=True)),
                ('testInstruction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defined_Grate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(blank=True, default=0, null=True)),
                ('two', models.IntegerField(blank=True, default=0, null=True)),
                ('three', models.IntegerField(blank=True, default=0, null=True)),
                ('four', models.IntegerField(blank=True, default=0, null=True)),
                ('five', models.IntegerField(blank=True, default=0, null=True)),
                ('six', models.IntegerField(blank=True, default=0, null=True)),
                ('seven', models.IntegerField(blank=True, default=0, null=True)),
                ('eight', models.IntegerField(blank=True, default=0, null=True)),
                ('nine', models.IntegerField(blank=True, default=0, null=True)),
                ('ten', models.IntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('toFromPair', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_Id', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('totalCount', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('industry_Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('ans1', models.CharField(blank=True, max_length=200, null=True)),
                ('ans2', models.CharField(blank=True, max_length=200, null=True)),
                ('ans3', models.CharField(blank=True, max_length=200, null=True)),
                ('ans4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans5', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_6To9.define_classes')),
                ('industry', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_6To9.industry_category')),
            ],
        ),
    ]
