# Generated by Django 3.2.7 on 2021-12-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_6To9', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Define_Classes',
            new_name='DefineClasses',
        ),
        migrations.RenameModel(
            old_name='Defined_Grate',
            new_name='DefinedGrate',
        ),
        migrations.RenameModel(
            old_name='Industry_Category',
            new_name='IndustryCategory',
        ),
    ]
