# Generated by Django 3.2.7 on 2021-12-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_6To9', '0005_auto_20211208_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='question',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
