# Generated by Django 3.2.7 on 2021-12-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_6To9', '0007_alter_reports_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation_6th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleImportance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation_6th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('interpretationTitle', models.TextField(blank=True, null=True)),
                ('YouCanDoPoint_1', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_2', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_3', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_4', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_5', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='interpretatio',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretatio', to='Test_6To9.interpretation_6th'),
        ),
    ]
