# Generated by Django 3.2.7 on 2021-12-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_6To9', '0009_showgrade_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showgrade',
            name='area',
        ),
    ]
