# Generated by Django 3.2.7 on 2021-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_6To9', '0010_remove_showgrade_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='definedgrate',
            name='P_11',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='definedgrate',
            name='P_12',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='definedgrate',
            name='P_13',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='definedgrate',
            name='P_14',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='definedgrate',
            name='P_15',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
