# Generated by Django 3.2.7 on 2021-12-16 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefineClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=200, null=True)),
                ('testInstruction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefinedGrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(blank=True, default=0, null=True)),
                ('two', models.IntegerField(blank=True, default=0, null=True)),
                ('three', models.IntegerField(blank=True, default=0, null=True)),
                ('four', models.IntegerField(blank=True, default=0, null=True)),
                ('five', models.IntegerField(blank=True, default=0, null=True)),
                ('six', models.IntegerField(blank=True, default=0, null=True)),
                ('seven', models.IntegerField(blank=True, default=0, null=True)),
                ('eight', models.IntegerField(blank=True, default=0, null=True)),
                ('nine', models.IntegerField(blank=True, default=0, null=True)),
                ('ten', models.IntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('toFromPair', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation_12th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleImportance', models.TextField(blank=True, null=True)),
                ('VerbalAbility', models.TextField(blank=True, null=True)),
                ('NumericalAbility', models.TextField(blank=True, null=True)),
                ('AbstractReasoning', models.TextField(blank=True, null=True)),
                ('LogicalReasoningAbility', models.TextField(blank=True, null=True)),
                ('MechanicalAbility', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_Id', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation_10th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('interpretationTitle', models.TextField(blank=True, null=True)),
                ('YouCanDoPoint_1', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_2', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_3', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_4', models.CharField(blank=True, max_length=200, null=True)),
                ('YouCanDoPoint_5', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_12th.defineclasses')),
            ],
        ),
        migrations.CreateModel(
            name='Reports_12th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('a', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('e', models.IntegerField(blank=True, null=True)),
                ('totalCount', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('industry_Grade', models.CharField(blank=True, max_length=200, null=True)),
                ('interpretatio', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretatio', to='Test_12th.interpretation_10th')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('a', models.CharField(blank=True, max_length=300, null=True)),
                ('b', models.CharField(blank=True, max_length=300, null=True)),
                ('c', models.CharField(blank=True, max_length=300, null=True)),
                ('d', models.CharField(blank=True, max_length=300, null=True)),
                ('e', models.CharField(blank=True, max_length=300, null=True)),
                ('rightAns', models.CharField(blank=True, max_length=300, null=True)),
                ('industry', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_12th.industrycategory')),
            ],
        ),
    ]
