# Generated by Django 3.2.7 on 2021-12-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_12th', '0002_auto_20211216_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='rightAns',
        ),
    ]
