# Generated by Django 3.2.7 on 2021-12-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='ans1',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ans2',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ans3',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ans4',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ans5',
            new_name='e',
        ),
        migrations.RenameField(
            model_name='reports_10th',
            old_name='ans1',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='reports_10th',
            old_name='ans2',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='reports_10th',
            old_name='ans3',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='reports_10th',
            old_name='ans4',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='reports_10th',
            old_name='ans5',
            new_name='e',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='grade',
        ),
    ]
