# Generated by Django 3.2.7 on 2021-12-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0002_auto_20211207_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='e',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rightAns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports_10th',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
