# Generated by Django 3.2.7 on 2021-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0003_auto_20211207_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='a',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='b',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='c',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='d',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='e',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rightAns',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
