# Generated by Django 3.2.7 on 2021-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0004_auto_20211208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='rightAns',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
