# Generated by Django 3.2.7 on 2021-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0005_alter_questions_rightans'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation_10th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleImportance', models.TextField(blank=True, null=True)),
                ('VerbalAbility', models.TextField(blank=True, null=True)),
                ('NumericalAbility', models.TextField(blank=True, null=True)),
                ('AbstractReasoning', models.TextField(blank=True, null=True)),
                ('LogicalReasoningAbility', models.TextField(blank=True, null=True)),
                ('MechanicalAbility', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
