# Generated by Django 3.2.7 on 2021-12-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0007_interpretation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interpretation',
            new_name='Interpretation_10th',
        ),
        migrations.AddField(
            model_name='reports_10th',
            name='interpretatio',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_10.interpretation_10th'),
        ),
    ]
