# Generated by Django 3.2.7 on 2021-12-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_10', '0008_auto_20211214_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_10th',
            name='interpretatio',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretatio', to='Test_10.interpretation_10th'),
        ),
    ]
