# Generated by Django 3.2.7 on 2021-12-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_7th', '0003_auto_20211215_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definedgrate',
            name='P_11',
        ),
        migrations.RemoveField(
            model_name='definedgrate',
            name='P_12',
        ),
        migrations.RemoveField(
            model_name='definedgrate',
            name='P_13',
        ),
        migrations.RemoveField(
            model_name='definedgrate',
            name='P_14',
        ),
        migrations.RemoveField(
            model_name='definedgrate',
            name='P_15',
        ),
    ]
