# Generated by Django 3.2.7 on 2021-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_8th', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='e',
        ),
        migrations.AddField(
            model_name='questions',
            name='rightAns',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='a',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='8th'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='b',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='8th'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='c',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='8th'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='d',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='8th'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='8th'),
        ),
    ]
